/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_gozen_gozenlogotest_LogoRecognize */

#ifndef _Included_com_gozen_gozenlogotest_LogoRecognize
#define _Included_com_gozen_gozenlogotest_LogoRecognize

#include "common.h"
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jdouble JNICALL Java_com_gzads_recognition_LogoRecognize_logoMatchTemplatPath
        (JNIEnv *env, jobject obj, jstring tmppath_, jstring mskpath_, jstring imgpath_,
         jint x, jint y, jint w, jint h);

#ifdef __cplusplus
}
#endif

#endif
