/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_gozen_gozenlogotest_LogoRecognize */

#ifndef _Included_com_gozen_gozenlogotest_LogoRecognize
#define _Included_com_gozen_gozenlogotest_LogoRecognize

#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif

double logoMatchTemplat(char* tmppath_, char* mskpath_, char* imgpath_,
         int x, int y, int w, int h);

#ifdef __cplusplus
}
#endif

#endif

